name: Publish new release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Create NPM release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@github.com"
      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      #      - run: yarn run build
      #      - run: yarn test
      - run: npm publish --verbose --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git add package.json
      - run: git commit -m 'Bump version'
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
